[tool.poetry]
name = "debugging"
version = "0.1.0"
description = ""
authors = ["Liam Gower <lee.gower17@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
